### ISSUE TITLE
macOS Sierra compilation

### ISSUE THREAD

**Issue by kitchenknif** [DavidPowell/OpenModes#2]
Not sure if this counts as an issue, but (macOS compilation instructions, maybe?)...

To compile under macOS, need to setup actual gcc, since bundled clang doesn't support OpenMP,
after that, need to tell setup.py to use gcc instead of clang. Also, a line break bug crops up while compiling fortran codes...

0. install python3 dependencies
1. install gmsh
(Homebrew: brew install homebrew/science/gmsh)
2. Manually install GCC 
(Homebrew: brew install gcc)
3. prepend /usr/local/bin to PATH
4. in setup.py add
os.environ["CC"] = "gcc-7"
os.environ["CXX"] = "gcc-7"
5. in rwg.f90 add another line break (for some reason ...) at line 1261:
                call face_integral_MFIE(num_integration, xi_eta, weights, nodes_q, &
                                    num_integration, xi_eta, weights, nodes_p, gamma_0, normals(p, :), T_form, &
                                    extract_singular, I_Z, I_Z_dgamma)

After that, package complies.

**Comment by DavidPowell** [comment]
@kitchenknif Thank you for these detailed instructions. I assume that you already saw the related issue #1.

I have fixed the code problems and added your instructions to the docs. The solution may be somewhat fragile, e.g.  if brew installs a different gcc version it will fail.

If you could test that the latest HEAD version runs without any modifications that would be appreciated.

**Comment by kitchenknif** [comment]
Latest HEAD builds out of the box without modifications.

Yes, I had initially symlinked /usr/local/bin/gcc-7 to /usr/local/bin/gcc, 
and set the compilers in setup.py to gcc, but that masks system default gcc, which may or may not be desired by the user, so I reverted to this less invasive but more fragile method.

Yes, I saw issue #1. 

BTW a couple of tests fail (not always the same ones, which is a bit weird) -
- test_srr_pair_separate_poles
- test_srr_pair_combined_poles
on the last run (both with a shape mismatch)

**Comment by DavidPowell** [comment]
Thanks for the confirmation @kitchenknif 

Thanks also for highlighting the failing tests. I've raised this as a separate issue #3, it's just a problem with the lack of robustness of the tests, not with the code itself.

**Comment by DavidPowell** [comment]
**Note:** There is now an option to install openmodes as a self-contained [docker image](http://openmodes.readthedocs.io/en/latest/install.html#docker-image-quick-option-2), which can eliminate the need for this complex installation procedure.
