### ISSUE TITLE
Calculations with realistic parameters diverge from Mie theory

### ISSUE THREAD

**Issue by kitchenknif** [DavidPowell/OpenModes#4]
EFIE operator, when fed a Drude-Lorentz model of a metal, diverges from Mie theory calculations

CTF operator, when fed a realistic model of a dielectric diverges from Mie theory calculations when noticeable losses are present in the system. 

*I know the manual says that these features are not tested / supported*, but theoretically the formulation should not impose any restrictions on the materials used.

All calculations were carried out for spherical particles.

- Silicon (Loss of the quadrupole mode by OpenModes is probably related to meshing of the sphere):
    - 170nm diameter
    - Material parameters taken from https://refractiveindex.info/?shelf=main&book=Si&page=Vuye-20C
![silicon](https://user-images.githubusercontent.com/8235105/27898908-b24d038e-625a-11e7-8dcf-7f42efae74d2.png)

 - Ag
    - 150nm radius
    - Drude-Lorentz permittivity 
        - eps_inf = 1
        - w_p = 2.321*10e15 Hz
        - gamma = 5.514*10e12 Hz
![ag](https://user-images.githubusercontent.com/8235105/27899928-cc66c382-625e-11e7-9457-a24609f5db52.png)

- Source Code
[OpenModesTests.zip](https://github.com/DavidPowell/OpenModes/files/1127027/OpenModesTests.zip)

**Comment by DavidPowell** [comment]
@kitchenknif Thanks for the report. Here are a few comments based on my initial checks:

- Lossy dielectrics should be fine, it is only the plasmonic metals which I haven't tested

- According to the time-convention used in OpenModes, imaginary parts of permittivity should be negative. Your code appears to show them positive. Can you please check if this is the problem?

- For the EFIE operator, only PEC materials are implemented in OpenModes. When using the surface equivalent model, the EFIE is not stable for penetrable objects. It needs to be somehow combined with the MFIE, to yield a stable formulation. Many such formulations exist, two of which  are implemented in OpenModes: the CTF and PMCHWT. Hopefully one of these will give you reasonable results.

**Comment by kitchenknif** [comment]
Yes, silicon with negative imaginary part of permittivity does the job nicely.
Plasmonic almost ideally follows Mie theory with CTF formulation.

Where can I read a bit more about the different formulations used in OpenModes? 
The documentation is a bit sparse on the topics, focusing on EFIE mostly. 

- Silicon Sphere, 170nm
![silicon_negimag](https://user-images.githubusercontent.com/8235105/27904439-40af23fa-626f-11e7-905a-f0f5a1b227f4.png)
- Ag Sphere, 150nm
![ag](https://user-images.githubusercontent.com/8235105/27904477-5a1be80a-626f-11e7-8a97-f4defc8dd8e7.png)

**Comment by DavidPowell** [comment]
Thanks for the feedback. I have added some details of the mathematical background to the documentation, including references. See http://openmodes.readthedocs.io/en/latest/maths.html

**Comment by kitchenknif** [comment]
Thanks!

Just to finish off my tests of a plasmonic sphere - the PMCHWT does even better.
![ag_pmchwtoperator](https://user-images.githubusercontent.com/8235105/28050568-003cca14-6631-11e7-9e29-26f1b6ce62b1.png)

**Comment by Green66S** [comment]
@kitchenknif  Hi, could you please share the code about the scattering efficiency? Many thanks.
