### ISSUE TITLE
Cannot pickle calculated impedances

### ISSUE THREAD

**Issue by kitchenknif** [DavidPowell/OpenModes#5]
Attempting to pickle calculated impedances results in an error
`AttributeError: Can't pickle local object 'wrap_if_constant.<locals>.<lambda>'`

This is not so much a bug of OpenModes as much as a limitation of Python itself, but being able to pickle/unpickle impedance matrices for reuse be nice. 
Is there an easy way to work around this (not necessarily using pickle, any way of dumping and loading the impedance matrices), or fix the incompatibility with python pickle?

Working example:
```
import numpy as np
import os.path as osp
import pickle

# import the openmodes packages
import openmodes
from openmodes.material import IsotropicMaterial
from openmodes.operator.penetrable import CTFOperator

# Params
c = 299792458.
num_freqs = 2
mesh_tol = 1
radius = 85*10**-9

freqs = np.linspace(c/(900*10**-9), c/(300*10**-9), num_freqs)


def mat(s):  # s = 2j * pi * Hz
    return 2.52**2

sim = openmodes.Simulation(operator_class=CTFOperator)
filename = osp.join(openmodes.geometry_dir, "Sphere.geo")
mesh = sim.load_mesh(filename, mesh_tol, parameters={'radius': radius})
material = IsotropicMaterial("Dielectric", mat, 1)
part = sim.place_part(mesh, material=material)

Zs = []
for freq_count, s in sim.iter_freqs(freqs):
    Z = sim.impedance(s)
    Zs.append({
                "Z": Z,
                "s": s,
                "count": freq_count
               })
    print(freq_count)


with open("./Z.dat", "wb") as f:
    pickle.dump(Zs, f)
```

**Comment by DavidPowell** [comment]
Yes, this is a known limitation of Python's pickle module, it cannot deal with python lambda functions, which are included in the material constants. All referenced objects such as the mesh, basis function, material properties etc are pickled when you pickle to impedance matrix. The workaround is to use the 3rd party library dill, which does not have this limitation.

So replacing `import pickle` with `import dill as pickle` should solve the problem, so long as you have the python module dill installed.

**Comment by kitchenknif** [comment]
Thanks, that worked.
