### ISSUE TITLE
KeyError: 'triangle'

### ISSUE THREAD

**Issue by Green66S** [DavidPowell/OpenModes#7]
When I run test_sphere.py or others, I have the error shown below: 
Traceback (most recent call last):

  File "E:\OpenModes-master\test\test_sphere.py", line 124, in <module>
    test_extinction_all(plot_extinction=True, skip_asserts=True)

  File "E:\OpenModes-master\test\test_sphere.py", line 76, in test_extinction_all
    sphere = sim.load_mesh(osp.join(mesh_dir, 'sphere.msh'))

  File "d:\Users\Green\anaconda3\lib\site-packages\openmodes\simulation.py", line 482, in load_mesh
    raw_mesh = gmsh.read_mesh_meshio(meshed_name)

  File "d:\Users\Green\anaconda3\lib\site-packages\openmodes\mesh\gmsh.py", line 344, in read_mesh_meshio
    if 'gmsh:physical' in mesh.cell_data['triangle']:

KeyError: 'triangle'

**Comment by Green66S** [comment]
nvm, i have fixed it.

**Comment by DavidPowell** [comment]
No worries. Feel free to share the details in case someone else has the same issue.

**Comment by Green66S** [comment]
@DavidPowell After I obtain the coefficient  = Z.solve(V). How could I plot the current or field? Is there any function I can use in OpenModes?

**Comment by DavidPowell** [comment]
Do you want something like [this example](https://nbviewer.jupyter.org/github/DavidPowell/openmodes-examples/blob/master/How%20to%20create%203D%20plots.ipynb) showing several ways of 3D plotting current and surface charge?

This and other examples can be found in the separate [openmodes-examples repo](https://github.com/DavidPowell/openmodes-examples).

**Comment by Green66S** [comment]
@DavidPowell Yes, many thanks for your help
